### ISSUE TITLE
When multiple trades are done, only the first trade done is activated and is processed

### ISSUE THREAD

**Issue by SRG1903** [SuperNETorg/dICOApp#11]
Even if multiple trades are done, only the first Trade gets activated and is processed.
There is no progress on all the other trades. 
https://www.screencast.com/t/zI53B4bRpa

**Comment by satindergrewal** [comment]
I think that is expected ?? It's not a GUI issue. Please ask @jl777 in #tradebots channel in SuperNET slack.
