### ISSUE TITLE
native daemon interference with electrum mode

### ISSUE THREAD

**Issue by ca333** [SuperNETorg/dICOApp#12]
when monaize daemon is running in the background the dICO-app try to use its rpc api although the electrum mode has been choosed. So issuing a  KMD or MNZ send will end up in an error or sending from the wrong wallet/daemon. Somehow the dICO-smartaddress gets imported into the native daemon once a transaction comes in.

**Comment by satindergrewal** [comment]
This sounds like a `marketmaker` issue, so must be talked with @jl777 
Please confirm with James and then let me know if I need to do or change anything with GUI.
