### ISSUE TITLE
The MNZ balance under Your Balance section dosen't match the Total to Buy under the Auto Traders list

### ISSUE THREAD

**Issue by SRG1903** [SuperNETorg/dICOApp#13]
The "Total to Buy" under the Auto traders list is 20, 
but in your balance section I see only 18.3175873 MNZ.
https://www.screencast.com/t/zI53B4bRpa

**Comment by satindergrewal** [comment]
Total **To** buy is the bot's setting, which says that that is what you have set the bot to buy and after that pause it's operation.
Total Bought, is wrong, and it's a bug. So, I'm removing that from next iteration.

Thanks for reporting. 👍
