### ISSUE TITLE
The trading still continues after the completion of 100% 

### ISSUE THREAD

**Issue by SRG1903** [SuperNETorg/dICOApp#14]
The trading after reaching 100% completion still continues to trade. 
Which increases the value of Total Bought under Auto Traders List as well.
https://www.screencast.com/t/zI53B4bRpa

**Comment by wtf-AnotherAccount** [comment]
still occurring with v0.5.7

Auto Trader ID | 3471684479
Auto Trade Name | buy_MNZ_KMD.1510299906

**Comment by satindergrewal** [comment]
this issue is not specific to GUI. More of Backend `marketmaker` API. Please talk to @jl777 on SuperNET slack directly.
