### ISSUE TITLE
KMD balance not fetching in Electrum mode.

### ISSUE THREAD

**Issue by himu007** [SuperNETorg/dICOApp#15]
Tried v0.5.6 in Ubuntu 16.04. KMD get activated on electrum mode slowly, shows the address but the balance never shows up. Did not find the issue while running both coins in native mode.

**Comment by satindergrewal** [comment]
this doesn't sound like GUI issue. please ask @jl777 or @cipig about it.

**Comment by CHMEX** [comment]
I have the same issue on Windows dICOApp-win64-x64-0.5.7-beta

dICOApp does **not** show the balance
BarterDex Builog App **shows** the balance in electrum mode.

thus suggests it's something in dICOApp which is not working properly.

**Comment by satindergrewal** [comment]
wait for electrum improvements that @jl777 has coded in recent updates. Those will be included in next release. I still don't agree it's GUI issue.

**Comment by himu007** [comment]
Yes, this is not a GUI issue. This is backend issue.
