### ISSUE TITLE
typos on various popup messages

### ISSUE THREAD

**Issue by ptyx11** [SuperNETorg/dICOApp#2]
<img width="316" alt="screen shot 2017-11-08 at 7 22 16 pm" src="https://user-images.githubusercontent.com/32718517/32567027-3a55650c-c4ba-11e7-8678-9ced4c3712e4.png">
<img width="325" alt="screen shot 2017-11-08 at 6 20 26 pm" src="https://user-images.githubusercontent.com/32718517/32567035-3df0c7e2-c4ba-11e7-9881-298dc2c624c1.png">

**Comment by satindergrewal** [comment]
fixed
