### ISSUE TITLE
Worng Sum(KMD) & Maximum Amount to Buy

### ISSUE THREAD

**Issue by himu007** [SuperNETorg/dICOApp#20]
![screenshot from 2017-11-14 23-38-32](https://user-images.githubusercontent.com/8881040/32811035-9bfa1b56-c995-11e7-8f92-ea1d9229f0a9.png)

1. The KMD sum displayed on `ASKS` are wrong. At price 0.31110122 KMD per MNZ × 0.13593473 MNZ (max) = Total price should be 0.04228946 KMD, or different with 20% or 30% bonus structure.

2. On Manual trading, when I click on any ASK order, it fills up price in KMD, pubkey of seller,  and It'll cost you. The `Max Amount to Buy` box shows wrong info. The amount shows on `It'll cost you` is the max amount available to buy.

**Comment by satindergrewal** [comment]
think this is solved? so closing. please open it again if not solved.
