### ISSUE TITLE
Wrong "Expires in" Date and Time

### ISSUE THREAD

**Issue by himu007** [SuperNETorg/dICOApp#21]
On swap details the `Expires in` date and time is incorrect. Showing 12 Nov 2017 while I'm executing the order on 15th Nov 2017.

![screenshot from 2017-11-15 00-19-06](https://user-images.githubusercontent.com/8881040/32812115-385308d2-c99b-11e7-9814-b64c62deaa0f.png)
![screenshot from 2017-11-15 00-20-01](https://user-images.githubusercontent.com/8881040/32812116-387138f2-c99b-11e7-88c4-0814a29ae4b4.png)

**Comment by satindergrewal** [comment]
fixed in https://github.com/SuperNETorg/dICOApp/commit/2b5cc78e1e537ec6370354608e1073f3d1bf90fe
