### ISSUE TITLE
enhancement.  Barter Completed!! Buyer Received Funds! Screen (close button)

### ISSUE THREAD

**Issue by alberm** [SuperNETorg/dICOApp#22]
SWAP Completed but I cant close the status window below anymore as the close button is somewhere at end where I cant scroll.
Have a close button somewhere else or let ESC or clicking back to the Trading screen allow to close the window.

![image](https://user-images.githubusercontent.com/3889718/32819732-2a5c184c-c9cb-11e7-9d00-814cd7159e4e.png)

**Comment by alberm** [comment]
right with TAP I get down to the close button.

**Comment by satindergrewal** [comment]
It is intended behavior, else your experience will be slower on GUI side.
