### ISSUE TITLE
Not getting the exact amount in price to buy field

### ISSUE THREAD

**Issue by Nagaws** [SuperNETorg/dICOApp#23]
when selected on trading pair am not getting the exact amount in pricebuy, getting  higher price

Selected ask "0.1838848" where price to buy I see 0.18572365

expected : It should display same amt as selected on ask field

**Comment by satindergrewal** [comment]
That's because the click option automatically adds `1%` additional calculated price to the input field. I will add some notification or reference to it adding 1% somewhere.
