### ISSUE TITLE
Buy order Notification issue

### ISSUE THREAD

**Issue by Nagaws** [SuperNETorg/dICOApp#24]
Placed order 0.01 MNZ, getting three Toaster msgs saying bot executed and other says try with  bigger denomination, I see order any way placed

Expected :  Order should'nt be placed if it doesnt resolve minimal conditions

![image](https://user-images.githubusercontent.com/30923430/32965404-52ac727c-cc11-11e7-8fef-ea632b37062f.png)

**Comment by satindergrewal** [comment]
It's not he MNZ amount, it's the relvalue amount which counts to be either 0.01 or the base value to be 0.01. Please test again and open this issue in BarterDEX-SImple if still exists in latest builds.
