### ISSUE TITLE
continue/complete failed trade from GUI

### ISSUE THREAD

**Issue by CHMEX** [SuperNETorg/dICOApp#27]
It happens from time to time that funds are stuck in temporary addresses.

Here an example:

https://kmd.explorer.supernet.org/address/bKgMpymxa5cRcmN3xSxY9Bh4i8XndTprg8

bKgMpymxa5cRcmN3xSxY9Bh4i8XndTprg8 received funds but did not spend it.

with JLs help I managed to complete the trade myself here are the steps which should be implemented via gui if detected it can even auto executed - no need for the user to get involved.

1)   .finished file has a warning: {"warning":"swaps in critical section","critical":1511421139,"endcritical":0,"expiration":1511436698,"tradeid":786549214,"requestid":316583474,"quoteid":3261084571,"iambob":0,"Bgui":"","Agui":"simp

2)  delete .finished file in DB / SWAP folder

3) call swap status with requestid and quoteid

curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"swapstatus\",\"requestid\":**316583474**,\"quoteid\":**3261084571**}"

the funds should be spent instantly an both parties are happy.

**Comment by satindergrewal** [comment]
coded this feature in latest commit on BarterDEX-Simple repo:
https://github.com/SuperNETorg/BarterDEX-Simple/commit/e87b49a3eae79acb3d08d81f82d1fb5725f31bda
Please don't use this repo to make issues anymore for BarterDEX/dICOApp.
This repo is obsolete now.
Use BarterDEX's own repo for making issues further.

https://github.com/SuperNETorg/BarterDEX-Simple
