### ISSUE TITLE
VCRuntime140.dll missing Windows 2016 

### ISSUE THREAD

**Issue by CHMEX** [SuperNETorg/dICOApp#8]
![image](https://user-images.githubusercontent.com/33424502/32605147-984af578-c550-11e7-9f11-873fbb0d24c7.png)

Fresh installation without 2015 Redistributable

Visual C++ Redistributable for Visual Studio 2015
https://www.microsoft.com/en-US/download/details.aspx?id=48145

might be a good idea to install if it's missing? I know the agama installer does that, but if you want to run it in electrum this package is needed,

**Comment by satindergrewal** [comment]
yes, good thing you noticed and provided a solution. should have covered in documentation and guide! 👍
