### ISSUE TITLE
Progress bar shows attempts, not progress

### ISSUE THREAD

**Issue by ptyx11** [SuperNETorg/dICOApp#9]
it does not actually show the progress of the swap. it goes up with the attempts
<img width="609" alt="screen shot 2017-11-09 at 2 02 56 pm" src="https://user-images.githubusercontent.com/32718517/32606952-79a1dbbc-c557-11e7-99a5-5b01c7ee073e.png">

**Comment by satindergrewal** [comment]
removed this progress bar. as per latest updates and discuss the result could be varied in different situations, so this progress bar at this point didn't make sense. so removed it.
